### ISSUE TITLE
Can't install in Laravel 8 project

### ISSUE THREAD

**Issue by eliyas5044** [Shipu/bkash#8]
Thank you for your great work. I have tried to install it in Laravel 8 with PHP 8, but getting a composer requirement issue for guzzlehttp/guzzle. As in laravel 8, composer locked at guzzle v7, but one of your packages *nahid/apiz* locked at guzzle v6. Please fix your requirement issue to install in Laravel 8.

![Screenshot 2021-02-16 at 2 07 07 PM](https://user-images.githubusercontent.com/13916443/108043301-289b2580-706b-11eb-859e-ea29f1a75277.png)

**Comment by AminulBD** [comment]
See the pull #10

**Comment by eliyas5044** [comment]
@AminulBD Thanks :)
